services:
  php:
    container_name: php-balance
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  nginx:
    container_name: nginx-balance
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - laravel-network

  postgres:
    container_name: postgres-balance
    image: postgres:15
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-balance
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@balance.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  postgres_data:
